environment: development

apphost: k8s

label:
  name: PrintCalculator

container:
  name: printcalculator-api
  pullPolicy: IfNotPresent
  image: hhglobal-printcalculatork8s
  tag: v1
  port: 80
replicas: 1

service:
  port: 8888
  securePort: 9999
  type: ClusterIP
